# _config.yml

url: "https://awelvor.github.io/root/"
title: "Jekyll Actions Demo"
collections:
  authors:
   output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
   
   
